Add root span helper in tracer
appsignal/appsignal-nodejs pull request #436
Opened 2021-08-25 12:37 UTC by luismiramirez

[skip changeset]

### Commit messages

The actual root span wasn't accessible as there were no helpers nor sets
for it. Making adding errors a difficult or impossible task if tried from nested span contexts.

This commit allows access to the root span from everywhere through the
tracer using similar storage as scopes, so we keep taking advantage of
Async Hooks to make it safe for async contexts.

### Current status

`Tracer.rootSpan()` is already implemented; to track errors properly into the root spans, we must add a new helper function into the `Tracer` class. This is almost done, but I need to update the interfaces in `@appsignal/types` before pushing it to test all the wrappers properly.

### Steps

- [x] Add access to the root span from the tracer
- [ ] Add new functions and properties including `addError()` to Tracer and Span type interfaces (https://github.com/appsignal/appsignal-javascript/blob/main/packages/types/src/interfaces/)
- [ ] Implement `addError()` Tracer function.
- [ ] Allow `addError()` to be called only from `RootSpan`s
- [ ] Deprecate old `addError()` from `BaseSpan`

2021-08-25 14:27 UTC, thijsc reviewed
Looks sensible so far!

2021-09-06 12:05 UTC, tombruijn requested changes
I still need to test this PR in a test app, but left some feedback so far.

2021-09-06 12:05 UTC, tombruijn commented on packages/apollo-server/src/index.ts
> -import { NodeClient } from "@appsignal/types"
I think we should keep the types. They're also useful for our users who use TypeScript and use types from our library. This way they don't need to specify `any` as argument types.

We can update the interfaces in types package in the javascript repo if needed.

2021-09-06 12:05 UTC, tombruijn commented on packages/nodejs/.changesets/add-global-error-tracking-helper--improve-root-span-management-.md
> +Add global error tracking helper. Improve root span management.
```suggestion
Add [`tracer.addError` helper function](https://docs.appsignal.com/nodejs/tracing/exception-handling.html) to set errors on the root span. If errors were set on child spans they were ignored.
```
It's a message for the user, so we should explain how the change impacts them. We should also update the linked page to explain how `tracer.addError` works.

2021-09-16 08:58 UTC, closed without merging