Deprecate using a filename in logPath
appsignal/appsignal-nodejs pull request #500
Opened 2021-11-15 14:02 UTC by luismiramirez

Using a filename in the logPath config option is no longer supported.
Now, if a filename is received, a deprecation message is shown and the
provided filename is changed to `appsignal.log`

Closes #490

2021-11-15 16:06 UTC, unflxw commented on packages/nodejs/src/config.ts
> +        `DEPRECATED: File names are no longer supported in the 'log_path config option.
```suggestion
        `DEPRECATED: File names are no longer supported in the 'log_path' config option.
```

2021-11-15 16:19 UTC, unflxw commented on packages/nodejs/src/__tests__/config.test.ts
>        it("uses the overwritten path", () => {
nitpick: maybe this test name could now say "uses the overwritten path **but changes the file name**"?

2021-11-16 07:40 UTC, tombruijn requested changes

2021-11-16 07:40 UTC, tombruijn commented on packages/nodejs/.changesets/deprecate-passing-a-file-to-logpath-config-option.md
> +Deprecate passing a file to logPath config option
```suggestion
Print deprecation message when passing a filename to `logPath` config option. This was already deprecated. Not it prints a warning message on app start.
```

2021-11-16 07:40 UTC, tombruijn commented on packages/nodejs/src/config.ts
> +        `DEPRECATED: File names are no longer supported in the 'log_path' config option.
```suggestion
        `DEPRECATED: File names are no longer supported in the 'logPath' config option.
```

2021-11-16 07:40 UTC, tombruijn commented on packages/nodejs/src/__tests__/config.test.ts
> +      it("uses the overwritten path but changes the file name", () => {
Can you also add an assertion here that the deprecation warning is being printed to `console.warn`?

2021-11-16 08:47 UTC, jeffkreeftmeijer approved these changes

2021-11-16 09:04 UTC, tombruijn approved these changes

2021-11-16 11:26 UTC, merged