Use APPSIGNAL_ACTIVE environment value
appsignal/appsignal-nodejs pull request #548
Opened 2022-01-17 14:54 UTC by unflxw

Before this change, the value of the `APPSIGNAL_ACTIVE` environment variable would never be read, as the `active` config option was read directly from the `BaseClient` constructor. After this change, the option is read from the `Config` object, after it has been initialised in the constructor.

Fixes #546.

2022-01-17 15:09 UTC, tombruijn requested changes
I see the same problem exists in the diagnose tool here: https://github.com/appsignal/appsignal-nodejs/blob/c77ff63e416c6cae41e699cc245559614035a9fb/packages/nodejs/src/diagnose.ts#L40-L42

It defaults to "active: true" on line 40, and only uses the diagnose's "true" value as the active option's value for the extension loading.

Can you update that part to match the new fixed behavior?

2022-01-17 16:09 UTC, unflxw commented
@tombruijn I have addressed it for the configuration object. The diagnose will now always show `active` to be `false` unless `APPSIGNAL_ACTIVE` is set to true. I have not changed it for the extension, as it is necessary for the extension to start in order to obtain diagnostic information from it -- the extension is always given `{active: true}` as an argument.

2022-01-17 16:41 UTC, tombruijn commented
> I have not changed it for the extension, as it is necessary for the extension to start in order to obtain diagnostic information from it -- the extension is always given {active: true} as an argument.

Yes those two things should not be related to one another and should be separated. I've created an issue to fix that: https://github.com/appsignal/appsignal-nodejs/issues/551

2022-01-17 16:42 UTC, tombruijn approved these changes

2022-01-18 08:36 UTC, luismiramirez approved these changes

2022-01-18 08:53 UTC, jeffkreeftmeijer approved these changes

2022-01-18 09:04 UTC, merged